Ret 2956
hmcts/et-data-model pull request #174
Opened 2023-03-17 16:15 UTC by paul-peasegood

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-2956

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-17 16:20 UTC, Itay-Kirsh submitted a review, later dismissed

2023-03-17 16:22 UTC, JackReevies requested changes

2023-03-17 16:22 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/items/GenericTypeItem.java
> +}
Excellent, hopefully we can use this pattern going forward. Will save a lot of manual work declaring XTypeItems

2023-03-17 16:22 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondNotificationType.java
> +
double blank line?

2023-03-17 16:22 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondNotificationType.java
> +    private String respondNotificationIsThis;
Might be worth taking the opportunity to rename this, it caused confusion earlier on CaseData

2023-03-17 16:22 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondNotificationType.java
> +
double blank line?

2023-03-17 16:46 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondNotificationType.java
> +    private String respondNotificationCMOorRequest;
respondNotificationCmoOrRequest

2023-03-17 16:52 UTC, JackReevies approved these changes

2023-03-20 09:46 UTC, Itay-Kirsh approved these changes

2023-03-20 09:46 UTC, merged