RET-3857: Add private hearing question as part of initial consideration (E&W) + (Scotland)
hmcts/et-data-model pull request #279
Opened 2023-07-17 10:52 UTC by jip1984

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-3857

### Change description ###
added icListingPreliminaryHearing to the CaseData

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-07-17 12:51 UTC, robin-ieong submitted a review, later dismissed

2023-07-18 08:48 UTC, JackReevies approved these changes

2023-07-18 11:31 UTC, JackReevies requested changes
bump ver in gradle

2023-07-18 13:39 UTC, robin-ieong approved these changes

2023-07-18 13:41 UTC, JackReevies approved these changes

2023-07-18 13:42 UTC, merged