RET-3460-Final - Refactor GenericTypeItem to TypeItem
hmcts/et-data-model pull request #358
Opened 2023-12-05 10:15 UTC by aaronjduffy

https://tools.hmcts.net/jira/browse/RET-3460

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2023-12-07 15:13 UTC, JackReevies commented on build.gradle
> +    implementation 'com.github.hmcts:et-data-model:RET-3460-Final-SNAPSHOT'
Why is this here? the data model shouldnt be importing itself

2023-12-07 15:18 UTC, JackReevies requested changes

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationType.java
> +    private List<TypeItem<PseResponseType>> respondCollection;
This can be `ListTypeItem<PseResponseType>`

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationType.java
> +    private List<TypeItem<RespondNotificationType>> respondNotificationTypeCollection;
```suggestion
    private ListTypeItem<RespondNotificationType> respondNotificationTypeCollection;
```

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/TseAdminRecordDecisionType.java
> +    private List<TypeItem<DocumentType>> responseRequiredDoc;
```suggestion
    private ListTypeItem<DocumentType> responseRequiredDoc;
```

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/TseRespondType.java
> +    private List<TypeItem<DocumentType>> supportingMaterial;
```suggestion
    private ListTypeItem<DocumentType> supportingMaterial;
```

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/TseRespondType.java
> +    private List<TypeItem<DocumentType>> addDocument;
```suggestion
    private ListTypeItem<DocumentType> addDocument;
```

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
> +    private List<TypeItem<HearingBundleType>> bundlesClaimantCollection;
```suggestion
    private ListTypeItem<HearingBundleType> bundlesClaimantCollection;
```

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
> +    private List<TypeItem<HearingBundleType>> bundlesRespondentCollection;
```suggestion
    private ListTypeItem<HearingBundleType> bundlesRespondentCollection;
```

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
> +    private List<TypeItem<DocumentType>> pseRespondentOrdReqUploadDocument;
```suggestion
    private ListTypeItem<DocumentType> pseRespondentOrdReqUploadDocument;
```

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
> +    private List<TypeItem<DocumentType>> tseAdminResponseRequiredNoDoc;
```suggestion
    private ListTypeItem<DocumentType> tseAdminResponseRequiredNoDoc;
```

2023-12-07 15:18 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
> +    private List<TypeItem<DocumentType>> tseAdminResponseRequiredYesDoc;
```suggestion
    private ListTypeItem<DocumentType> tseAdminResponseRequiredYesDoc;
```

2023-12-12 09:32 UTC, lvo700 approved these changes

2023-12-13 09:06 UTC, JackReevies approved these changes

2023-12-13 09:07 UTC, JackReevies requested changes
Can't use 4.0.0 because you've previously published this. 4.0.1 should work though?

2024-01-30 13:54 UTC, marcjudge submitted a review, later dismissed

2024-01-30 18:53 UTC, JackReevies requested changes

2024-01-30 18:53 UTC, JackReevies commented on build.gradle
> +
This is a breaking change thus it needs to be a MAJOR bump. Think Fergus is about to release 4.0.0 so maybe choose 5.0.0

2024-01-30 18:53 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/et/common/model/ccd/types/PseResponse.java
> +    private List<TypeItem<DocumentType>> supportingMaterial;
`ListTypeItem<DocumentType>` not `List<TypeItem<DocumentType>>`

2024-08-14 14:26 UTC, closed without merging